package EducatorProfile;

public class Educator_TestData {
    public String refresh_token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOnsidXNlcl9pZCI6IjM0MzI1Njc4NjU0MyIsInJvbGUiOiJlZHVjYXRvciJ9LCJleHAiOjE3MTYzNzk5MjcuNDk2NzU2LCJ0eXBlIjoicmVmcmVzaCIsImp0aSI6IjYxNzcwODJjOTkyNDQzNWU4NmFlYTg3NmVlN2Q4NDk1In0.h2VC8kbzOkhhtNIhFoeCDxrHWG75pQZgMy3V-ThGTLU";
    public String educator_id = "343256786543";
    public String deleted_educator = "206130172222";
    public String notActive_educator = "206130172111";
    public String refresh_token_for_deletedEducator ="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOnsidXNlcl9pZCI6IjIwNjEzMDE3MjIyMiIsInJvbGUiOiJlZHVjYXRvciJ9LCJleHAiOjE3MTU5Mzc2MTQuNDM0MzIsInR5cGUiOiJyZWZyZXNoIiwianRpIjoiZTQ3YjljOWFkMTgxNDAxYTlkOTgzY2YzNzk3NjlmNmYifQ.PnRZ5Olu8SYUxXbL3JclAQRG5NN9F2g51xhrwFEuQRI";
    public String  refresh_token_for_notActiveEducator ="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOnsidXNlcl9pZCI6IjIwNjEzMDE3MjExMSIsInJvbGUiOiJlZHVjYXRvciJ9LCJleHAiOjE3MTU5Mzc2NDQuNTYzNTM4LCJ0eXBlIjoicmVmcmVzaCIsImp0aSI6ImVlYzQ1M2QyNDNjZjQ1ZjRiM2Y0ZWQ4NTNjZWMyMDIwIn0.IxWDDLYzVnfG6KoF-0_vNVMS5uc-ZQtWqJRoUYa-Fro";



}
