package ParentAccount

class Parent_TestData {
    public String Parent_refreshToken ="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOnsiY3JlYXRlX2FjY291bnRfZm9yIjoic3R1ZGVudF9wYXJlbnRAbmFnd2EuY29tIiwidG9rZW5fc2NvcGUiOiJjcmVhdGVfYWNjb3VudCJ9LCJleHAiOjE3MTkyMjk1MDUuODEyMDk1LCJ0eXBlIjoicmVmcmVzaCIsImp0aSI6ImVlMmJmYmYzZjk5ZDQ0ZmZiZWQxNzZjZTY1MmVhZjJjIn0.2v9oIDCMLpZPgvIQM3gMzXHCeaKZzmp0jwh41AZHG5I";

}
